### PR TITLE
Add cache suffixes

### LINKED ISSUE #1: Implement `cache-dependency-path` equivalent
I was about to post this issue over in baipp but this might be a better place for it.

The default cache key  `${{runner.os}}-uv` is not fine-grained enough to work with a heterogeneous CI/CD pipeline with separated build and test steps, because the requirements to build may be very different from the requirements to run and test. since baipp runs first, it will have a cache miss and save the uv cache for the build step, then any subsequent run using setup-cached-uv will have a cache hit, but only primed for the build dependencies and unable to update the cache with additional test dependencies.

[Hopefully setup-python will eventually have `cache: uv`](https://github.com/actions/setup-python/issues/822) but until then it would be swell if I could add:
```
- uses: hynek/setup-cached-uv
  with:
    cache-dependency-path: '**/requirements-dev.txt'
```
which would result in cache keys like:
```
setup-cached-uv-Linux-22.04-Ubuntu-python-3.12.2-de25a2691d32d697d64ac0f45eb15fbab0ef7c4ca684a123bb5ec913fb6498d0
```

### PR DESCRIPTION
**Pull request by hynek**
attempt at fixing #1

### CODE REVIEW

**Comment by hynek** [comment]
hey @richardsheridan – is this worth finishing up?

**Comment by richardsheridan** [comment]
Absolutely! I'll be the first one (probably) to use it, if you merge it. I suggest noting that the OS is part of the cache key already in the `cache-suffix` description.

**Comment by hynek** [comment]
@richardsheridan how does https://github.com/hynek/setup-cached-uv/blob/fb5be2cbc3550761677a786fad039fedd8f2ef73/README.md look?

**Comment by richardsheridan** [comment]
Very clear, thanks!

**Pull request merged**
