### PR TITLE
Fix quotings

### LINKED ISSUE #17: v2.2.0: Cache path broken for Ubuntu
The devguide docs build passed on `main` two days ago, on Ubuntu:

https://github.com/python/devguide/actions/runs/10666808924

Here's a devguide docs build of `main`, failing today:

```
/home/runner/work/devguide/devguide/"/tmp/scu-uv-cache"/archive-v0/LZw1MOw0z-Porf5QiCanY/sphinx-8.0.2.dist-info/LICENSE.rst:55: WARNING: Inline literal start-string without end-string. [docutils]
/home/runner/work/devguide/devguide/"/tmp/scu-uv-cache"/archive-v0/LZw1MOw0z-Porf5QiCanY/sphinx-8.0.2.dist-info/LICENSE.rst:67: ERROR: Document may not end with a transition. [docutils]
```

https://github.com/python/devguide/actions/runs/10770128668/job/29862846750#step:5:85

That cache path looks broken, I think it should be an absolute `/tmp/scu-uv-cache` path instead of a local one. This causes our tooling to check for RST errors in files in the cache, which we don't care about.

Here's a passing build today, but pinning to v2.1.0 of the action:

https://github.com/hugovk/devguide/actions/runs/10770299577

### PR DESCRIPTION
**Pull request by hynek**
fixes #17 m(

### CODE REVIEW

**Comment by hynek** [comment]
hey @hugovk, any chance you could check if 5d471f055d5fc47ffc5df8d2e23485eab18e25e5? It should, but if I could save myself another embarrassing release…

**Comment by hugovk** [comment]
With: https://github.com/hugovk/devguide/commit/6bc17495ee3adbde2adb5fb68bc6ab82d7312648

After 6 minutes it's still waiting for a runner...

https://github.com/hugovk/devguide/actions/runs/10773845107/job/29874533866

**Comment by hugovk** [comment]
I just had to go and get a cup of tea and it passed now, thanks!

**Comment by hynek** [comment]
awesome thanks!

**Pull request merged**
