### PR TITLE
Make workflow and jobs names part of the cache key

### PR DESCRIPTION
**Pull request by hynek**

### CODE REVIEW

**Comment by hynek** [comment]
hm @henryiii would you agree that it would be better if `GitHub.job` were part of the default suffix? That's ultimately what 99.999% of people want and 90% of them will forget to do the right thing, so maybe _we_ should?

**Comment by hynek** [comment]
Or to rephrase: how important is it to share caches between jobs?

I feel like if it's that important, we should rather add an absolute `cache-key` input to let people completely override it.

**Comment by henryiii** [comment]
Yes, I think this makes sense.

**Comment by hynek** [comment]
jftr, I've also added a weekly cache in #11 bust and bumped major so nobody can complain. the cache bust can be easily disabled tho

**Comment by henryiii** [comment]
I thought it already has an timeout of a week built in? Oh, I guess the difference is that the built-in one will evict the cache if it hasn’t been touched in a week, while this will evict every week?

**Comment by hynek** [comment]
yep exactly! the built-in one doesn't expire if you access it every 5.5 days

**Pull request merged**
